##------------------������ʱ��------------------
set_property IOSTANDARD LVCMOS33 [get_ports start_pg]
set_property IOSTANDARD LVCMOS33 [get_ports conf_btn]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstn_fpga]
set_property IOSTANDARD LVCMOS33 [get_ports btn1]
set_property IOSTANDARD LVCMOS33 [get_ports btn2]
set_property IOSTANDARD LVCMOS33 [get_ports btn3]
set_property PACKAGE_PIN R11 [get_ports start_pg]
set_property PACKAGE_PIN R15 [get_ports conf_btn]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rstn_fpga]
set_property PACKAGE_PIN U4 [get_ports btn1]
set_property PACKAGE_PIN V1 [get_ports btn2]
set_property PACKAGE_PIN R17 [get_ports btn3]

##------------------���뿪��------------------
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_data[11]}]

set_property PACKAGE_PIN V5 [get_ports {switch_data[8]}]
set_property PACKAGE_PIN V2 [get_ports {switch_data[9]}]
set_property PACKAGE_PIN U2 [get_ports {switch_data[10]}]
set_property PACKAGE_PIN U3 [get_ports {switch_data[11]}]
set_property PACKAGE_PIN R1 [get_ports {switch_data[0]}]
set_property PACKAGE_PIN N4 [get_ports {switch_data[1]}]
set_property PACKAGE_PIN M4 [get_ports {switch_data[2]}]
set_property PACKAGE_PIN R2 [get_ports {switch_data[3]}]
set_property PACKAGE_PIN P2 [get_ports {switch_data[4]}]
set_property PACKAGE_PIN P3 [get_ports {switch_data[5]}]
set_property PACKAGE_PIN P4 [get_ports {switch_data[6]}]
set_property PACKAGE_PIN P5 [get_ports {switch_data[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {base}]
set_property PACKAGE_PIN T3 [get_ports {base}]

##-------------------�߶������?------------------
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en[7]}]
set_property PACKAGE_PIN G1 [get_ports {digit_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {digit_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {digit_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {digit_en[0]}]
set_property PACKAGE_PIN G2 [get_ports {digit_en[7]}]
set_property PACKAGE_PIN C2 [get_ports {digit_en[6]}]
set_property PACKAGE_PIN C1 [get_ports {digit_en[5]}]
set_property PACKAGE_PIN H1 [get_ports {digit_en[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sseg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[7]}]
set_property PACKAGE_PIN D4 [get_ports {sseg[6]}]
set_property PACKAGE_PIN E3 [get_ports {sseg[5]}]
set_property PACKAGE_PIN D3 [get_ports {sseg[4]}]
set_property PACKAGE_PIN F4 [get_ports {sseg[3]}]
set_property PACKAGE_PIN F3 [get_ports {sseg[2]}]
set_property PACKAGE_PIN E2 [get_ports {sseg[1]}]
set_property PACKAGE_PIN D2 [get_ports {sseg[0]}]
set_property PACKAGE_PIN H2 [get_ports {sseg[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[7]}]

set_property PACKAGE_PIN B4 [get_ports {sseg1[6]}]
set_property PACKAGE_PIN A4 [get_ports {sseg1[5]}]
set_property PACKAGE_PIN A3 [get_ports {sseg1[4]}]
set_property PACKAGE_PIN B1 [get_ports {sseg1[3]}]
set_property PACKAGE_PIN A1 [get_ports {sseg1[2]}]
set_property PACKAGE_PIN B3 [get_ports {sseg1[1]}]
set_property PACKAGE_PIN B2 [get_ports {sseg1[0]}]
set_property PACKAGE_PIN D5 [get_ports {sseg1[7]}]

##------------------ps2�ӿ�------------------
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
set_property PACKAGE_PIN K5 [get_ports ps2_clk]
set_property PACKAGE_PIN L4 [get_ports ps2_data]

##------------------uart------------------
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN N5 [get_ports rx]
set_property PACKAGE_PIN T4 [get_ports tx]

##------------------led------------------
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_LED[15]}]
set_property PACKAGE_PIN K3 [get_ports {reg_LED[0]}]
set_property PACKAGE_PIN M1 [get_ports {reg_LED[1]}]
set_property PACKAGE_PIN L1 [get_ports {reg_LED[2]}]
set_property PACKAGE_PIN K6 [get_ports {reg_LED[3]}]
set_property PACKAGE_PIN J5 [get_ports {reg_LED[4]}]
set_property PACKAGE_PIN H5 [get_ports {reg_LED[5]}]
set_property PACKAGE_PIN H6 [get_ports {reg_LED[6]}]
set_property PACKAGE_PIN K1 [get_ports {reg_LED[7]}]
set_property PACKAGE_PIN K2 [get_ports {reg_LED[8]}]
set_property PACKAGE_PIN J2 [get_ports {reg_LED[9]}]
set_property PACKAGE_PIN J3 [get_ports {reg_LED[10]}]
set_property PACKAGE_PIN H4 [get_ports {reg_LED[11]}]
set_property PACKAGE_PIN J4 [get_ports {reg_LED[12]}]
set_property PACKAGE_PIN G3 [get_ports {reg_LED[13]}]
set_property PACKAGE_PIN G4 [get_ports {reg_LED[14]}]
set_property PACKAGE_PIN F6 [get_ports {reg_LED[15]}]

set_property SEVERITY {Warning} [get_drc_checks REQP-1712]